apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-util
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: util
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: util
    spec:
      containers:
      - image: host.docker.internal:5000/blog-adamw523-util
        name: util
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
